Exercise 1 : Array Creation and Manipulation
Instructions
Create a 1D NumPy array containing numbers from 0 to 9.

Expected Output:



array([0, 1, 2, 3, 4, 5, 6, 7, 8, 9])

In [3]:
import numpy as np
array = np.arange(10)
array

array([0, 1, 2, 3, 4, 5, 6, 7, 8, 9])

Exercise 2 : Type Conversion and Array Operations
Instructions
Convert a list [3.14, 2.17, 0, 1, 2] into a NumPy array and convert its data type to integer.

Expected Output:



array([3, 2, 0, 1, 2])

In [8]:
my_list = [3.14, 2.17, 0, 1, 2]
my_array = np.array(my_list)
my_array = my_array.astype(int)
print(my_array)

[3 2 0 1 2]


Exercise 3 : Working with Multi-Dimensional Arrays
Instructions
Create a 3x3 NumPy array with values ranging from 1 to 9.

Expected Output:



array([[1, 2, 3],
       [4, 5, 6],
       [7, 8, 9]])

In [ ]:
array = np.arange(1, 10).reshape(3, 3) #Arranges an array in range 1 - 10 not inclusive so we get 1-9. Reshapes the array into 3X3.
print(array)

[[1 2 3]
 [4 5 6]
 [7 8 9]]


Exercise 4 : Creating Multi-Dimensional Array with Random Numbers
Instructions
Create a 2D NumPy array of shape (4, 5) filled with random numbers.

Expected Output:



array([[0.56, 0.85, 0.01, 0.42, 0.68],
       [0.22, 0.37, 0.73, 0.93, 0.39],
       [0.44, 0.03, 0.87, 0.02, 0.83],
       [0.78, 0.87, 0.98, 0.80, 0.46]])

In [ ]:
array = np.random.rand(4, 5) # Generates random numbers between 0 and 1 (uniform distribution) Shape is defined as 4X5.
array = np.round(array, 2) # Rounds the values to a specified number of decimal places
print(array)

[[0.61 0.62 0.04 0.95 0.43]
 [0.69 0.34 0.41 0.67 0.01]
 [0.55 0.42 0.3  0.35 0.05]
 [0.56 0.16 0.72 0.08 0.74]]


Exercise 5 : Indexing Arrays
Instructions
Select the second row from a given 2D NumPy array.

Expected Output:



array = np.array([[21,22,23,22,22],[20, 21, 22, 23, 24],[21,22,23,22,22]])

In [16]:
this_array = np.array([[21,22,23,22,22],[20, 21, 22, 23, 24],[21,22,23,22,22]])
second_row = this_array[1]
print(second_row)


[20 21 22 23 24]


Exercise 6 : Reversing elements
Instructions
Reverse the order of elements in a given 1D NumPy array (first element becomes last).

Expected Output:



array([9, 8, 7, 6, 5, 4, 3, 2, 1, 0])




In [17]:
that_array = np.arange(10)
reversed_array = that_array[::-1]
print(reversed_array)

[9 8 7 6 5 4 3 2 1 0]


Exercise 7 : Identity Matrix
Instructions
Create a 4x4 identity matrix using NumPy.

Expected Output:



array([[1., 0., 0., 0.],
       [0., 1., 0., 0.],
       [0., 0., 1., 0.],
       [0., 0., 0., 1.]])


In [19]:
identity_matrix = np.eye(4)
identity_matrix

array([[1., 0., 0., 0.],
       [0., 1., 0., 0.],
       [0., 0., 1., 0.],
       [0., 0., 0., 1.]])

Exercise 8 : Simple Aggregate Funcs
Instructions
Find the sum and average of a given 1D array.

Expected Output:



Sum: 45, Average: 4.5


In [22]:
array = np.arange(50) # Create an array in the range of 50 (0-49)
print(array)

total_sum = np.sum(array)
average = np.mean(array)

print(f"Sum: {total_sum}, Average: {average}")

[ 0  1  2  3  4  5  6  7  8  9 10 11 12 13 14 15 16 17 18 19 20 21 22 23
 24 25 26 27 28 29 30 31 32 33 34 35 36 37 38 39 40 41 42 43 44 45 46 47
 48 49]
Sum: 1225, Average: 24.5


Exercise 9 : Create Array and Change its Structure
Instructions
Create a NumPy array with elements from 1 to 20; then reshape it into a 4x5 matrix.

Expected Output:



array([[ 1,  2,  3,  4,  5],
       [ 6,  7,  8,  9, 10],
       [11, 12, 13, 14, 15],
       [16, 17, 18, 19, 20]])


In [26]:
array = np.arange(1, 21).reshape(4, 5)
#array = array.reshape(2, 10)
#array = array.reshape(10, 2)
print(array)

[[ 1  2  3  4  5]
 [ 6  7  8  9 10]
 [11 12 13 14 15]
 [16 17 18 19 20]]


Exercise 10 : Conditional Selection of Values
Instructions
Extract all odd numbers from a given NumPy array.

Expected Output:



array([1, 3, 5, 7, 9])

In [27]:
array = np.arange(100)
odd_numbers = array[array % 2 != 0]
print(odd_numbers)


[ 1  3  5  7  9 11 13 15 17 19 21 23 25 27 29 31 33 35 37 39 41 43 45 47
 49 51 53 55 57 59 61 63 65 67 69 71 73 75 77 79 81 83 85 87 89 91 93 95
 97 99]
