## Numpy Library

A list of numbers in python is very similar to a 1D numpy array

In [6]:
l = [1,2,3,4,5]

2D Array ->

In [4]:
li = [
    [5.2, 3.0, 4.5],
    [9.1, 0.1, 0.3]
]
print(li)

[[5.2, 3.0, 4.5], [9.1, 0.1, 0.3]]


3D Array ->

In [5]:
threeD_array = [
    [
        [1,4,7],
        [2,9,7],
        [1,3,0],
        [9,6,9]
    ],
    [
        [2,3,4],
        [1,1,5],
        [1,1,2],
        [1,1,3]
    ]
]

In [3]:
import numpy as np

We can make arrays in a bunch of ways, the simplest is using python lists

In [46]:
ar1 = np.array(l)
print(ar1)
print(l)

[1 2 3 4 5]
[1, 2, 3, 4, 5]


In [10]:
ar2 = np.array(li)
print(ar2)
print('----------------')
print(li)

[[5.2 3.  4.5]
 [9.1 0.1 0.3]]
----------------
[[5.2, 3.0, 4.5], [9.1, 0.1, 0.3]]


We can analyze the shape and size of our arrays

In [11]:
print(ar2.shape, ar2.size)

(2, 3) 6


Python lists don't quite understand the dimensions

In [12]:
print(len(li))

2


In [13]:
print(ar2.dtype)

float64


## Accessing Items in Arrays

In [14]:
ar2

array([[5.2, 3. , 4.5],
       [9.1, 0.1, 0.3]])

In [15]:
ar2[0,2]

np.float64(4.5)

In [20]:
threeD_array = np.array(threeD_array)
print(threeD_array)

[[[1 4 7]
  [2 9 7]
  [1 3 0]
  [9 6 9]]

 [[2 3 4]
  [1 1 5]
  [1 1 2]
  [1 1 3]]]


In [21]:
threeD_array[1,1,2]

np.int64(5)

In [ ]:
threeD_array[1,1,:] # equivalent to threeD_array[1,1,0:3]

array([1, 1, 5])

We can get that whole horizontal slice by taking all depth layers 

In [24]:
threeD_array[:,1,:]

array([[2, 9, 7],
       [1, 1, 5]])

We can also access items in an array by giving a list of indexes

In [47]:
ar1[np.array((1,3))]

array([2, 4])

In a one dimensional array we can take every other item by using the step option

In [25]:
ar1

array([1, 2, 3, 4, 5])

In [26]:
ar1[0:5:2] # ar1[start:stop:step] here step is 2

array([1, 3, 5])

We can take every other row/floor by using the step option with our indexing/slicing

In [27]:
threeD_array[:,::2,:]

array([[[1, 4, 7],
        [1, 3, 0]],

       [[2, 3, 4],
        [1, 1, 2]]])

We can access items with conditions

In [28]:
ar1 > 2

array([False, False,  True,  True,  True])

In [29]:
ar1[ar1 > 2]

array([3, 4, 5])

In [30]:
threeD_array == 1

array([[[ True, False, False],
        [False, False, False],
        [ True, False, False],
        [False, False, False]],

       [[False, False, False],
        [ True,  True, False],
        [ True,  True, False],
        [ True,  True, False]]])

In [31]:
threeD_array[threeD_array == 1]

array([1, 1, 1, 1, 1, 1, 1, 1])

We can change values in the array very simply

In [32]:
ar1[3] = 42
ar1

array([ 1,  2,  3, 42,  5])

In [33]:
threeD_array[threeD_array == 1] = 0
threeD_array

array([[[0, 4, 7],
        [2, 9, 7],
        [0, 3, 0],
        [9, 6, 9]],

       [[2, 3, 4],
        [0, 0, 5],
        [0, 0, 2],
        [0, 0, 3]]])

In [37]:
ar1[1:4] = -10
ar1

array([  1, -10, -10, -10,   5])

In [39]:
ar1[1:4] = [5,4,3]
ar1

array([1, 5, 4, 3, 5])

In [43]:
ar1[3:3] = [1,2,3,4,5,6]

ValueError: could not broadcast input array from shape (6,) into shape (0,)

## Numpy Random

In [48]:
np.random.randint(low=4,high=16,size=5)

array([ 8, 11, 14,  8, 12], dtype=int32)

We can create an array of numbers in order using numpy

In [53]:
numbers = np.arange(-10,11) #numbers = np.arange(-10,11,2) will give only evens
numbers

array([-10,  -9,  -8,  -7,  -6,  -5,  -4,  -3,  -2,  -1,   0,   1,   2,
         3,   4,   5,   6,   7,   8,   9,  10])

We can mix up an array of numbers with the permutation function

In [54]:
np.random.permutation(numbers)

array([  9, -10,  -8,  -5,  -1,  -2,  -7,   8,   5,   2,  -6,   7,  -9,
        -4,  10,  -3,   0,   3,   6,   1,   4])

## Array Math

In [55]:
a = np.array([1,2,3,4,5])
b = np.array([7,3,3,5,6])

In [56]:
a + 5

array([ 6,  7,  8,  9, 10])

In [65]:
print(a*5,a-5,a/5,a%2, a**3)

[ 5 10 15 20 25] [-4 -3 -2 -1  0] [0.2 0.4 0.6 0.8 1. ] [1 0 1 0 1] [  1   8  27  64 125]


In [66]:
a + b

array([ 8,  5,  6,  9, 11])

In [67]:
a * b

array([ 7,  6,  9, 20, 30])

In [77]:
ar2d = np.array([[5,6,7],
                 [8,7,6]])
y = np.array([[20],[30]])
ar2d

array([[5, 6, 7],
       [8, 7, 6]])

In [69]:
ar2d * 2

array([[10, 12, 14],
       [16, 14, 12]])

In [72]:
ar2d[0] = ar2d[0] * 3

In [73]:
ar2d

array([[15, 18, 21],
       [ 8,  7,  6]])

In [76]:
ar2d.shape, y.shape

((2, 3), (2, 1))

In [78]:
ar2d*y

array([[100, 120, 140],
       [240, 210, 180]])

In [79]:
print(ar2, threeD_array)

[[5.2 3.  4.5]
 [9.1 0.1 0.3]] [[[0 4 7]
  [2 9 7]
  [0 3 0]
  [9 6 9]]

 [[2 3 4]
  [0 0 5]
  [0 0 2]
  [0 0 3]]]


In [80]:
print(ar2.shape, threeD_array.shape)

(2, 3) (2, 4, 3)


We can reshape ar2 so that it looks like a row/floor of threeD_array

In [85]:
ar2  = ar2.reshape((2,1,3))
ar2.shape

(2, 1, 3)

In [86]:
ar2 + threeD_array

array([[[ 5.2,  7. , 11.5],
        [ 7.2, 12. , 11.5],
        [ 5.2,  6. ,  4.5],
        [14.2,  9. , 13.5]],

       [[11.1,  3.1,  4.3],
        [ 9.1,  0.1,  5.3],
        [ 9.1,  0.1,  2.3],
        [ 9.1,  0.1,  3.3]]])

In [87]:
ar2

array([[[5.2, 3. , 4.5]],

       [[9.1, 0.1, 0.3]]])

In [90]:
j = np.array([[1,2,3],[1,2,3]])
x = np.array([1,2])
x.shape

(2,)

In [91]:
j + x

ValueError: operands could not be broadcast together with shapes (2,3) (2,) 

In [95]:
long = np.arange(12)
long.reshape((6,2))

array([[ 0,  1],
       [ 2,  3],
       [ 4,  5],
       [ 6,  7],
       [ 8,  9],
       [10, 11]])

In [96]:
long.reshape((2,6))

array([[ 0,  1,  2,  3,  4,  5],
       [ 6,  7,  8,  9, 10, 11]])

In [97]:
r = long.reshape((6,2))
r.reshape((12))

array([ 0,  1,  2,  3,  4,  5,  6,  7,  8,  9, 10, 11])

In [99]:
r.reshape((3,4))

array([[ 0,  1,  2,  3],
       [ 4,  5,  6,  7],
       [ 8,  9, 10, 11]])

In [100]:
long.reshape((2,3,2))

array([[[ 0,  1],
        [ 2,  3],
        [ 4,  5]],

       [[ 6,  7],
        [ 8,  9],
        [10, 11]]])

## Aggregation Functions

In [101]:
long.sum()

np.int64(66)

In [102]:
long.mean()

np.float64(5.5)

In [103]:
long.min(), long.max()

(np.int64(0), np.int64(11))

In [ ]:
r

array([[ 0,  1],
       [ 2,  3],
       [ 4,  5],
       [ 6,  7],
       [ 8,  9],
       [10, 11]])

In [105]:
r.mean(axis=0)

array([5., 6.])

Converting an image to grayscale with PIL and mean

In [106]:
from PIL import Image
image = Image.open('Soldier.png')

In [109]:
imagear = np.array(image)
imagear.shape

(1024, 1792, 4)

In [114]:
imagear[0,:10,:10]

array([[ 11,   9,  37, 255],
       [  8,   5,  34, 255],
       [  4,   2,  30, 255],
       [  1,   0,  27, 255],
       [  1,   0,  27, 255],
       [  1,   0,  26, 255],
       [  2,   0,  26, 255],
       [  2,   0,  26, 255],
       [  2,   0,  26, 255],
       [  2,   0,  25, 255]], dtype=uint8)

In [117]:
gray = imagear.mean(axis=2)
gray = gray.round()
gray = gray.astype(np.uint8)
grayimage = Image.fromarray(gray)
grayimage.save('graysoldier.png')